### PR TITLE
Fix script and update

### PR DESCRIPTION
**Pull request by dayvsonsales**

### CODE REVIEW

**Comment by ahsand97** [comment]
There's a mistake in the file CAM4Recorder.py in the line 59, there's an **if** and an **and** with the same condition:
**if videoAppUrl == "" and videoAppUrl == "":**
And I think it was supposed to be like this:
**if videoAppUrl == "" and videoPlayUrl == "":**

**Comment by dayvsonsales** [comment]
@ahsand97 You're right.

**Comment by ajsr1989** [comment]
hello how are you sorry a question the script works for a windows operating system

**Comment by dayvsonsales** [comment]
@ajsr1989 I didn't test in Windows, so I don't know.

**Comment by ajsr1989** [comment]
ok well I ran a test script in windows to check if it worked and there was no problem, already speaking of the cam4 script when executing it I get an error in these lines

import requests, time, datetime, os, threading, sys, configparser
import uuid
from livestreamer import Livestreamer

Could you help me to verify what the error is, I thank you in advance

**Comment by dayvsonsales** [comment]
@ajsr1989 could you be more specific? Post the entire error stack. And please post it on the repository issues.

**Comment by ajsr1989** [comment]
THIS ERROR MESSAGE APPEARS DO NOT MUDULE NAMED 'requests'

**Comment by dayvsonsales** [comment]
@ajsr1989 this seems to be because you didn't install the required dependencies, but you didn't post the entire error stack, so I can't be more accurate about it.

**Comment by ajsr1989** [comment]
A thousand apologies for the delay in responding the full stack of errors is as follows

unresolved import requests

unresolved import livestreamer

incosistent whitespace

incosistent whitespace

It should be clarified that you check if the libraries were correctly downloaded and if they are

**Comment by dayvsonsales** [comment]
@ajsr1989 It seems like you didn't install the dependencies and modified the script putting some wrong whitespace.

**Pull request closed without merging**
